name: Escalation
favicon: null
layout_spectrum: 0.5711722357664257
typography_spectrum: 0.13240455044433475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050209'
    - '#8d5d4f'
    - '#21aebf'
    - '#eef8f7'
    - '#77e6e6'
  brandStrength: 0.5138374897651374
  lightness: 0.15133157093077898
  saturation: 0.2394202270079404
  rhythmicContrast: 0.7884415863081813
purpose: []
